Add firewall rules with nftables

diff --git a/start b/start
--- a/start
+++ b/start
@@ -13,4 +13,10 @@ if ! cp ./nsswitch.conf /etc/netns/nsvpn/nsswitch.conf; then
 	exit 1
 fi
 
+# Set up firewall if the nsvpn table does not already exist
+if ! ip netns exec nsvpn nft list table inet nsvpn >/dev/null && ! ip netns exec nsvpn nft -f ./nftables-commands.nft; then
+	echo "Could not set up firewall. Exiting early."
+	exit 1
+fi
+
 openvpn --route-noexec --ifconfig-noexec --script-security 2 --up-delay --up ./tunnelUp "$@"
